import type { WeaponDef, WeaponId } from "./types";

export const WEAPONS: Record<WeaponId, WeaponDef> = {
  knife: {
    id: "knife",
    name: "FACA",
    slot: 4,
    damage: 55,
    fireRate: 450,
    magazine: 1,
    reserve: 0,
    spread: 0,
    speed: 0,
    range: 1.4,
    reloadTime: 0,
    isMelee: true,
  },
  glock: {
    id: "glock",
    name: "GLOCK-18",
    slot: 2,
    damage: 28,
    fireRate: 170,
    magazine: 20,
    reserve: 120,
    spread: 0.04,
    speed: 38,
    range: 45,
    reloadTime: 1800,
  },
  usp: {
    id: "usp",
    name: "USP-S",
    slot: 2,
    damage: 33,
    fireRate: 200,
    magazine: 12,
    reserve: 100,
    spread: 0.03,
    speed: 40,
    range: 48,
    reloadTime: 1900,
  },
  deagle: {
    id: "deagle",
    name: "DESERT EAGLE",
    slot: 2,
    damage: 63,
    fireRate: 420,
    magazine: 7,
    reserve: 35,
    spread: 0.05,
    speed: 42,
    range: 50,
    reloadTime: 2200,
  },
  ak47: {
    id: "ak47",
    name: "AK-47",
    slot: 1,
    damage: 36,
    fireRate: 100,
    magazine: 30,
    reserve: 90,
    spread: 0.035,
    speed: 48,
    range: 55,
    reloadTime: 2400,
  },
};
